baseURL = "https://dubbo.apache.org/"
languageCode = "en-us"
title = "Apache Dubbo"
theme = ["github.com/google/docsy", "github.com/google/docsy/dependencies"]

enableGitInfo = true
enableRobotsTXT = true

# Language settings
contentDir = "content/zh-cn"
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = true
# Useful when translating.
enableMissingTranslationPlaceholders = true

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "G-1TFHM5YBH0"

staticDir = ["static"]

contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# Language configuration
[languages]
[languages.en]
title = "Apache Dubbo"
description = "Apache Dubbo Official Website"
languageName = "English"
contentDir = "content/en"
# Weight used for sorting.
weight = 1

[languages.zh-cn]
title = "Apache Dubbo"
description = "Apache Dubbo 官方网站"
languageName = "中文"
contentDir = "content/zh-cn"
#time_format_default = "02.01.2006"
#time_format_blog = "02.01.2006"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
# See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
style = "solarized-dark"
# Uncomment if you want your chosen highlight style used for code blocks without a specified language
guessSyntax = "true"

# Everything below this are Site Params

[params]
copyright = "The Apache Software Foundation. Apache and the Apache feather logo are trademarks of The Apache Software Foundation."
# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/apache/dubbo-website"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/apache/dubbo"
github_branch = "master"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

#gcs_engine_id = "011737558837375720776:fsdu1nryfng"

algolia_docsearch = true
offlineSearch = false


#[[menu.main]]
#    name = "Initializer"
#    weight = 50
#    url = "https://dubbo.apache.org/"
#    post = "<i class='fas fa-external-link-alt'></i>"
#[[menu.main]]
#    name = "Admin"
#    weight = 60
#    url = "https://dubbo.apache.org/"
#    post = "<i class='fas fa-external-link-alt'></i>"

#     post = "<span class='alert'>New</span>"

# Add Ecosystems
# en_ecosystem_docs_menu = "Advanced Docs"
# cn_ecosystem_docs_menu = "高级文档"
#
# [[params.ecosystems.docs]]
#   ecosystem = "Dubbo Java SDK"
#   en.docs.url = "https://chickenlj.github.io/incubator-dubbo-website/en/java-sdk/"
#   cn.docs.url = "https://chickenlj.github.io/incubator-dubbo-website/cn/java-sdk/"
#
# [[params.ecosystems.docs]]
#   ecosystem = "Dubbo Golang SDK"
#   en.docs.url = "https://chickenlj.github.io/incubator-dubbo-website/en/golang-sdk/"
#   cn.docs.url = "https://chickenlj.github.io/incubator-dubbo-website/cn/golang-sdk/"
#
# [[params.ecosystems.docs]]
#   ecosystem = "Dubbo Pixiu"
#   en.docs.url = "https://chickenlj.github.io/incubator-dubbo-website/en/pixiu/"
#   cn.docs.url = "https://chickenlj.github.io/incubator-dubbo-website/cn/pixiu/"
#
# [[params.ecosystems.docs]]
#   ecosystem = "Dubbo Admin"
#   en.docs.url = "https://chickenlj.github.io/incubator-dubbo-website/en/admin/"
#   cn.docs.url = "https://chickenlj.github.io/incubator-dubbo-website/cn/admin/"

# Enable syntax highlighting and copy buttons on code blocks with Prism
#prism_syntax_highlighting = false

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = false
# Set to true to disable the About link in the site footer
footer_about_disable = true
navbar_translucent_over_cover_disable = true

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/apache/dubbo-website/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/apache/dubbo-website/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page,
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = false

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
name = "Dubbo mailing list archive"
url = "https://lists.apache.org/list.html?dev@dubbo.apache.org"
icon = "fa fa-envelope"
desc = "Discussion and help from your fellow users"
#[[params.links.user]]
#name = "Bilibili"
#url = "https://space.bilibili.com/1395485052"
#icon = "fa-brands fa-bilibili"
#desc = "Follow us on Bilibili to get the latest news!"
#[[params.links.user]]
#	name = "Stack Overflow"
#	url = "https://example.org/stack"
#	icon = "fab fa-stack-overflow"
#        desc = "Practical questions and curated answers"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
name = "GitHub"
url = "https://github.com/apache/dubbo"
icon = "fab fa-github"
desc = "Development takes place here!"
#[[params.links.developer]]
#	name = "Slack"
#	url = "https://example.org/slack"
#	icon = "fab fa-slack"
#        desc = "Chat with other project developers"
[[params.links.developer]]
name = "Subscribe to mailing list"
url = "mailto:dev-subscribe@dubbo.apache.org"
icon = "fa fa-envelope"
desc = "Discuss development issues around the project"

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[taxonomies]
tag = "tags"
