site_name: Dubbo 2.7.8
repo_url: https://github.com/apache/dubbo-website/
edit_uri:
nav:
  - "用户手册":
      - "入门":
          - "背景": 'user/preface/background.md'
          - "需求": 'user/preface/background.md'
          - "架构": 'user/preface/architecture.md'
          - "用法": 'user/preface/usage.md'
      - "快速启动": 'user/quick-start.md'
      - "依赖": 'user/dependencies.md'
      - "成熟度": 'user/maturity.md'
      - "配置":
          - "XML 配置": 'user/configuration/xml.md'
          - "API 配置": 'user/configuration/api.md'
          - "Annotation 配置": 'user/configuration/annotation.md'
          - "动态配置中心": 'user/configuration/annotation.md'
          - "配置加载流程": 'user/configuration/configuration-load-process.md'
          - "自动加载环境变量": 'user/configuration/environment-variables.md'
      - "示例":
          - "启动时检查": 'user/demos/preflight-check.md'
          - "集群容错": 'user/demos/fault-tolerent-strategy.md'
          - "负载均衡": 'user/demos/loadbalance.md'
          - "线程模型": 'user/demos/thread-model.md'
          - "直连提供者": 'user/demos/explicit-target.md'
          - "只订阅": 'user/demos/subscribe-only.md'
          - "只注册": 'user/demos/registry-only.md'
          - "静态服务": 'user/demos/static-service.md'
          - "多协议": 'user/demos/multi-protocols.md'
          - "多注册中心": 'user/demos/multi-registry.md'
          - "服务分组": 'user/demos/service-group.md'
          - "多版本": 'user/demos/multi-versions.md'
          - "分组聚合": 'user/demos/group-merger.md'
          - "参数验证": 'user/demos/parameter-validation.md'
          - "结果缓存": 'user/demos/result-cache.md'
          - "泛化引用": 'user/demos/generic-reference.md'
          - "泛化实现": 'user/demos/generic-service.md'
          - "回声测试": 'user/demos/echo-service.md'
          - "上下文信息": 'user/demos/context.md'
          - "隐式参数": 'user/demos/attachment.md'
          - "异步调用": 'user/demos/async-call.md'
          - "服务端异步": 'user/demos/async-execute-on-provider.md'
          - "本地调用": 'user/demos/local-call.md'
          - "参数回调": 'user/demos/callback-parameter.md'
          - "事件通知": 'user/demos/events-notify.md'
          - "本地存根": 'user/demos/local-stub.md'
          - "本地伪装": 'user/demos/local-mock.md'
          - "延迟暴露": 'user/demos/delay-publish.md'
          - "并发控制": 'user/demos/concurrency-control.md'
          - "连接控制": 'user/demos/config-connection.md'
          - "延迟连接": 'user/demos/lazy-connect.md'
          - "粘滞连接": 'user/demos/stickiness.md'
          - "令牌验证": 'user/demos/token-authorization.md'
          - "路由规则": 'user/demos/routing-rule.md'
          - "配置规则": 'user/demos/config-rule.md'
          - "服务降级": 'user/demos/service-downgrade.md'
          - "优雅停机": 'user/demos/graceful-shutdown.md'
          - "主机绑定": 'user/demos/hostname-binding.md'
          - "日志适配": 'user/demos/logger-strategy.md'
          - "访问日志": 'user/demos/accesslog.md'
          - "服务容器": 'user/demos/service-container.md'
          - "分布式事务": 'user/demos/distributed-transaction.md'
          - "线程栈自动dump": 'user/demos/dump.md'
          - "Netty4": 'user/demos/netty4.md'
          - "Kryo和FST序列化": 'user/demos/serialization.md'
          - "简化注册中心URL": 'user/demos/simplify-registry-data.md'
          - "API 参考手册": 'user/demos/api.md'
      - "schema 配置参考手册":
          - "dubbo:service": 'user/references/xml/dubbo-service.md'
          - "dubbo:reference": 'user/references/xml/dubbo-reference.md'
          - "dubbo:protocol": 'user/references/xml/dubbo-protocol.md'
          - "dubbo:registry": 'user/references/xml/dubbo-registry.md'
          - "dubbo:monitor": 'user/references/xml/dubbo-monitor.md'
          - "dubbo:application": 'user/references/xml/dubbo-application.md'
          - "dubbo:module": 'user/references/xml/dubbo-module.md'
          - "dubbo:provider": 'user/references/xml/dubbo-provider.md'
          - "dubbo:consumer": 'user/references/xml/dubbo-consumer.md'
          - "dubbo:method": 'user/references/xml/dubbo-method.md'
          - "dubbo:argument": 'user/references/xml/dubbo-argument.md'
          - "dubbo:parameter": 'user/references/xml/dubbo-parameter.md'
          - "dubbo:config-center": 'user/references/xml/dubbo-config-center.md'
      - "协议参考手册":
          - "dubbo://": 'user/references/protocol/dubbo.md'
          - "rmi://": 'user/references/protocol/rmi.md'
          - "hessian://": 'user/references/protocol/hessian.md'
          - "http://": 'user/references/protocol/http.md'
          - "thrift://": 'user/references/protocol/thrift.md'
          - "rest://": 'user/references/protocol/rest.md'
      - "注册中心参考手册":
          - "Multicast 注册中心": 'user/references/registry/multicast.md'
          - "Zookeeper 注册中心": 'user/references/registry/zookeeper.md'
          - "Redis 注册中心": 'user/references/registry/redis.md'
          - "Simple 注册中心": 'user/references/registry/simple.md'
      - "元数据中心参考手册":
          - "Redis 元数据中心": 'user/references/metadata/metadata-redis.md'
          - "Zookeeper 元数据中心": 'user/references/registry/metadata-zookeeper.md'
      - "telnet 命令参考手册": 'user/references/telnet.md'
      - "在线运维命令-QOS": 'user/references/qos.md'
      - "maven 插件参考手册": 'user/references/maven.md'
      - "服务化最佳实践": 'user/best-practice.md'
      - "推荐用法": 'user/recommend.md'
      - "容量规划": 'user/capacity-plan.md'
      - "性能测试报告": 'user/perf-test.md'
      - "测试覆盖率报告": 'user/covergence.md'
      - "版本与升级":
          - "2.7.x升级步骤及注意事项": 'user/version-270.md'
  - "开发手册":
      - "源码构建": 'dev/build.md'
      - "框架设计": 'dev/design.md'
      - "扩展点加载": 'dev/SPI.md'
      - "实现细节": 'dev/implementation.md'
      - "SPI 扩展实现":
          - "协议扩展": 'dev/impls/protocol.md'
          - "调用拦截扩展": 'dev/impls/filter.md'
          - "引用监听扩展": 'dev/impls/invoker-listener.md'
          - "暴露监听扩展": 'dev/impls/exporter-listener.md'
          - "集群扩展": 'dev/impls/cluster.md'
          - "路由扩展": 'dev/impls/router.md'
          - "负载均衡扩展": 'dev/impls/load-balance.md'
          - "合并结果扩展": 'dev/impls/merger.md'
          - "注册中心扩展": 'dev/impls/registry.md'
          - "监控中心扩展": 'dev/impls/monitor.md'
          - "扩展点加载扩展": 'dev/impls/extension-factory.md'
          - "动态代理扩展": 'dev/impls/proxy-factory.md'
          - "编译器扩展": 'dev/impls/compiler.md'
          - "消息派发扩展": 'dev/impls/dispatcher.md'
          - "线程池扩展": 'dev/impls/threadpool.md'
          - "序列化扩展": 'dev/impls/serialize.md'
          - "网络传输扩展": 'dev/impls/remoting.md'
          - "信息交换扩展": 'dev/impls/exchanger.md'
          - "组网扩展": 'dev/impls/networker.md'
          - "Telnet 命令扩展": 'dev/impls/telnet-handler.md'
          - "状态检查扩展": 'dev/impls/status-checker.md'
          - "容器扩展": 'dev/impls/container.md'
          - "页面扩展": 'dev/impls/page.md'
          - "缓存扩展": 'dev/impls/cache.md'
          - "验证扩展": 'dev/impls/validation.md'
          - "日志适配扩展": 'dev/impls/logger-adapter.md'
          - "配置中心": 'dev/impls/config-center.md'
      - "公共契约": 'dev/contract.md'
      - "编码约定": 'dev/coding.md'
      - "设计原则":
          - "魔鬼在细节": 'dev/principals/code-detail.md'
          - "一些设计上的基本常识": 'dev/principals/general-knowledge.md'
          - "谈谈扩充式扩展与增量式扩展": 'dev/principals/expansibility.md'
          - "配置设计": 'dev/principals/configuration.md'
          - "设计实现的健壮性": 'dev/principals/robustness.md'
          - "防痴呆设计": 'dev/principals/dummy.md'
          - "扩展点重构": 'dev/principals/extension.md'
      - "编码约定": 'dev/release.md'
      - "编码约定": 'dev/contribution.md'
      - "编码约定": 'dev/checklist.md'
      - "编码约定": 'dev/code-smell.md'
      - "编码约定": 'dev/TCK.md'
  - "管理者文档":
    - "Dubbo Admin介绍": 'dev/introduction.md'
    - "服务搜索和详情": 'dev/serviceSearch.md'
    - "服务治理": 'dev/serviceGovernance.md'
    - "服务测试": 'dev/serviceTest.md'

theme:
  name: readthedocs
  collapse_navigation: true
  sticky_navigation: true
  titles_only: true

plugins:
  - search:
      separator: '[\s\-\.]+'
      min_search_length: 2
      lang: 'en'