site_name: Apache Dubbo
repo_url: https://github.com/apache/dubbo-website/
edit_uri: edit/master/documentations/2.7/en-us/docs/

# Configuration
theme:
  name: material
  custom_dir: overrides

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs
    #- instant
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - search

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/squidfunk
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/squidfunk/mkdocs-material
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/squidfunk/mkdocs-material/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/squidfunk/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/squidfunk

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - "Home": 'index.md'
  - "Docs":
    - "2.7":
      - "User's Guide":
        - "Preface":
            - "Bakcground": 'user/preface/background.md'
            - "Requirements": 'user/preface/background.md'
            - "Architecture": 'user/preface/architecture.md'
            - "Usage": 'user/preface/usage.md'
        - "Quick Start": 'user/quick-start.md'
        - "Dependencies": 'user/dependencies.md'
        - "Maturity": 'user/maturity.md'
        - "Configuration":
            - "XML Configuration": 'user/configuration/xml.md'
            - "API Configuration": 'user/configuration/api.md'
            - "Annotation Configuration": 'user/configuration/annotation.md'
        - "Demos":
            - "Check on start": 'user/demos/preflight-check.md'
            - "Fault tolerance": 'user/demos/fault-tolerent-strategy.md'
            - "Load balance": 'user/demos/loadbalance.md'
            - "Thread model": 'user/demos/thread-model.md'
            - "Connecting certain provider straightly": 'user/demos/explicit-target.md'
            - "Subscribe only": 'user/demos/subscribe-only.md'
            - "Register only": 'user/demos/registry-only.md'
            - "Static service": 'user/demos/static-service.md'
            - "Multi-protocols": 'user/demos/multi-protocols.md'
            - "Multi-registries": 'user/demos/multi-registry.md'
            - "Grouping": 'user/demos/service-group.md'
            - "Versions": 'user/demos/multi-versions.md'
            - "Group merger": 'user/demos/group-merger.md'
            - "Parameter validation": 'user/demos/parameter-validation.md'
            - "Result cache": 'user/demos/result-cache.md'
            - "Generic call": 'user/demos/generic-reference.md'
            - "Generic implementation": 'user/demos/generic-service.md'
            - "Echo service": 'user/demos/echo-service.md'
            - "Context": 'user/demos/context.md'
            - "Attachment": 'user/demos/attachment.md'
            - "Async call": 'user/demos/async-call.md'
            - "Local call": 'user/demos/local-call.md'
            - "Parameter callback": 'user/demos/callback-parameter.md'
            - "Event callback": 'user/demos/events-notify.md'
            - "Local stub": 'user/demos/local-stub.md'
            - "Local mock": 'user/demos/local-mock.md'
            - "Delay publish": 'user/demos/delay-publish.md'
            - "Concurrency limit": 'user/demos/concurrency-control.md'
            - "Connection limit": 'user/demos/config-connection.md'
            - "Lazy connec": 'user/demos/lazy-connect.md'
            - "Stickness connection": 'user/demos/stickiness.md'
            - "Token authorization": 'user/demos/token-authorization.md'
            - "Routing rule": 'user/demos/routing-rule.md'
            - "Config rule": 'user/demos/config-rule.md'
            - "Service downgrade": 'user/demos/service-downgrade.md'
            - "Graceful shutdown": 'user/demos/graceful-shutdown.md'
            - "Host binding": 'user/demos/hostname-binding.md'
            - "Logger": 'user/demos/logger-strategy.md'
            - "Accesslog": 'user/demos/accesslog.md'
            - "Container": 'user/demos/service-container.md'
            - "Transaction": 'user/demos/distributed-transaction.md'
            - "Thread dump": 'user/demos/dump.md'
            - "Netty4": 'user/demos/netty4.md'
            - "Kryo&FST serialization": 'user/demos/serialization.md'
            - "Simplified registry URL": 'user/demos/simplify-registry-data.md'
            - "API reference": 'user/demos/api.md'
        - "Schema reference":
            - "dubbo:service": 'user/references/xml/dubbo-service.md'
            - "dubbo:reference": 'user/references/xml/dubbo-reference.md'
            - "dubbo:protocol": 'user/references/xml/dubbo-protocol.md'
            - "dubbo:registry": 'user/references/xml/dubbo-registry.md'
            - "dubbo:monitor": 'user/references/xml/dubbo-monitor.md'
            - "dubbo:application": 'user/references/xml/dubbo-application.md'
            - "dubbo:module": 'user/references/xml/dubbo-module.md'
            - "dubbo:provider": 'user/references/xml/dubbo-provider.md'
            - "dubbo:consumer": 'user/references/xml/dubbo-consumer.md'
            - "dubbo:method": 'user/references/xml/dubbo-method.md'
            - "dubbo:argument": 'user/references/xml/dubbo-argument.md'
            - "dubbo:parameter": 'user/references/xml/dubbo-parameter.md'
            - "dubbo:config-center": 'user/references/xml/dubbo-config-center.md'
        - "Protocol reference":
            - "dubbo://": 'user/references/protocol/dubbo.md'
            - "rmi://": 'user/references/protocol/rmi.md'
            - "hessian://": 'user/references/protocol/hessian.md'
            - "http://": 'user/references/protocol/http.md'
            - "thrift://": 'user/references/protocol/thrift.md'
            - "rest://": 'user/references/protocol/rest.md'
        - "Registry reference":
            - "Multicast": 'user/references/registry/multicast.md'
            - "Zookeeper": 'user/references/registry/zookeeper.md'
            - "Redis": 'user/references/registry/redis.md'
            - "Simple": 'user/references/registry/simple.md'
        - "Metadata reference":
            - "Redis": 'user/references/metadata/metadata-redis.md'
            - "Zookeeper": 'user/references/registry/metadata-zookeeper.md'
        - "Telnet reference": 'user/references/telnet.md'
        - "Maven plugin reference": 'user/references/maven.md'
        - "Best practice": 'user/best-practice.md'
        - "Recommendation": 'user/recommend.md'
        - "Capacity plan": 'user/capacity-plan.md'
        - "Benchmark": 'user/perf-test.md'
        - "Code coverange": 'user/covergence.md'
      - "Developer's Guide":
        - "How to Build": 'dev/build.md'
        - "Architecture": 'dev/design.md'
        - "How SPI Works": 'dev/SPI.md'
        - "Init, Process, Protocols": 'dev/implementation.md'
        - "SPI Extensions":
          - "Protocol": 'dev/impls/protocol.md'
          - "Filter": 'dev/impls/filter.md'
          - "Invoker Listener": 'dev/impls/invoker-listener.md'
          - "Exporter Listener": 'dev/impls/exporter-listener.md'
          - "Cluster": 'dev/impls/cluster.md'
          - "Router": 'dev/impls/router.md'
          - "Load Balance": 'dev/impls/load-balance.md'
          - "Merge": 'dev/impls/merger.md'
          - "Registry": 'dev/impls/registry.md'
          - "Monitor": 'dev/impls/monitor.md'
          - "Extension Factory": 'dev/impls/extension-factory.md'
          - "Proxy Factory": 'dev/impls/proxy-factory.md'
          - "Compiler": 'dev/impls/compiler.md'
          - "Dispatcher": 'dev/impls/dispatcher.md'
          - "Threadpool": 'dev/impls/threadpool.md'
          - "Serialize": 'dev/impls/serialize.md'
          - "Remoting": 'dev/impls/remoting.md'
          - "Exchanger": 'dev/impls/exchanger.md'
          - "Networker": 'dev/impls/networker.md'
          - "Telnet Handler": 'dev/impls/telnet-handler.md'
          - "Status Checker": 'dev/impls/status-checker.md'
          - "Container": 'dev/impls/container.md'
          - "Page": 'dev/impls/page.md'
          - "Cache": 'dev/impls/cache.md'
          - "Validation": 'dev/impls/validation.md'
          - "Logger Adapter": 'dev/impls/logger-adapter.md'
        - "Contract": 'dev/contract.md'
        - "Coding": 'dev/coding.md'
        - "Release": 'dev/release.md'
        - "Contribution": 'dev/contribution.md'
        - "Checklist": 'dev/checklist.md'
        - "Code Smell": 'dev/code-smell.md'
        - "TCK": 'dev/TCK.md'
      - "Admin's Guide":
        - "Dubbo Admin Overview": 'admin/introduction.md'
        - "Search & Details": 'admin/serviceSearch.md'
        - "Governance": 'admin/serviceGovernance.md'
        - "Testing": 'admin/serviceTest.md'
    - "3.0":
        - "User's Guide":
            - "Preface":
                - "Bakcground": 'user/preface/background.md'
#  - "Blog":
#  - "Community":